/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardWallRouteImport } from './routes/dashboard.wall'
import { Route as DashboardTestimonialsRouteImport } from './routes/dashboard.testimonials'
import { Route as DashboardRequestsRouteImport } from './routes/dashboard.requests'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard.insights'
import { Route as DashboardImportsRouteImport } from './routes/dashboard.imports'
import { Route as DashboardFormsRouteImport } from './routes/dashboard.forms'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardWidgetsCreateRouteImport } from './routes/dashboard.widgets.create'
import { Route as DashboardTestimonialsIdRouteImport } from './routes/dashboard.testimonials.$id'
import { Route as DashboardSettingsWorkspaceRouteImport } from './routes/dashboard.settings.workspace'
import { Route as DashboardSettingsTeamRouteImport } from './routes/dashboard.settings.team'
import { Route as DashboardSettingsBillingRouteImport } from './routes/dashboard.settings.billing'
import { Route as DashboardSettingsApiKeysRouteImport } from './routes/dashboard.settings.api-keys'
import { Route as DashboardFormsCreateRouteImport } from './routes/dashboard.forms.create'
import { Route as CollectWorkspaceSlugFormSlugRouteImport } from './routes/collect.$workspaceSlug.$formSlug'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWallRoute = DashboardWallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestimonialsRoute = DashboardTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequestsRoute = DashboardRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImportsRoute = DashboardImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFormsRoute = DashboardFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWidgetsCreateRoute = DashboardWidgetsCreateRouteImport.update({
  id: '/widgets/create',
  path: '/widgets/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestimonialsIdRoute = DashboardTestimonialsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardTestimonialsRoute,
} as any)
const DashboardSettingsWorkspaceRoute =
  DashboardSettingsWorkspaceRouteImport.update({
    id: '/settings/workspace',
    path: '/settings/workspace',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsTeamRoute = DashboardSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsBillingRoute =
  DashboardSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsApiKeysRoute =
  DashboardSettingsApiKeysRouteImport.update({
    id: '/settings/api-keys',
    path: '/settings/api-keys',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFormsCreateRoute = DashboardFormsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardFormsRoute,
} as any)
const CollectWorkspaceSlugFormSlugRoute =
  CollectWorkspaceSlugFormSlugRouteImport.update({
    id: '/collect/$workspaceSlug/$formSlug',
    path: '/collect/$workspaceSlug/$formSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/forms': typeof DashboardFormsRouteWithChildren
  '/dashboard/imports': typeof DashboardImportsRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRouteWithChildren
  '/dashboard/wall': typeof DashboardWallRoute
  '/collect/$workspaceSlug/$formSlug': typeof CollectWorkspaceSlugFormSlugRoute
  '/dashboard/forms/create': typeof DashboardFormsCreateRoute
  '/dashboard/settings/api-keys': typeof DashboardSettingsApiKeysRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/team': typeof DashboardSettingsTeamRoute
  '/dashboard/settings/workspace': typeof DashboardSettingsWorkspaceRoute
  '/dashboard/testimonials/$id': typeof DashboardTestimonialsIdRoute
  '/dashboard/widgets/create': typeof DashboardWidgetsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/forms': typeof DashboardFormsRouteWithChildren
  '/dashboard/imports': typeof DashboardImportsRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRouteWithChildren
  '/dashboard/wall': typeof DashboardWallRoute
  '/collect/$workspaceSlug/$formSlug': typeof CollectWorkspaceSlugFormSlugRoute
  '/dashboard/forms/create': typeof DashboardFormsCreateRoute
  '/dashboard/settings/api-keys': typeof DashboardSettingsApiKeysRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/team': typeof DashboardSettingsTeamRoute
  '/dashboard/settings/workspace': typeof DashboardSettingsWorkspaceRoute
  '/dashboard/testimonials/$id': typeof DashboardTestimonialsIdRoute
  '/dashboard/widgets/create': typeof DashboardWidgetsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/forms': typeof DashboardFormsRouteWithChildren
  '/dashboard/imports': typeof DashboardImportsRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRouteWithChildren
  '/dashboard/wall': typeof DashboardWallRoute
  '/collect/$workspaceSlug/$formSlug': typeof CollectWorkspaceSlugFormSlugRoute
  '/dashboard/forms/create': typeof DashboardFormsCreateRoute
  '/dashboard/settings/api-keys': typeof DashboardSettingsApiKeysRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/team': typeof DashboardSettingsTeamRoute
  '/dashboard/settings/workspace': typeof DashboardSettingsWorkspaceRoute
  '/dashboard/testimonials/$id': typeof DashboardTestimonialsIdRoute
  '/dashboard/widgets/create': typeof DashboardWidgetsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/register'
    | '/dashboard/analytics'
    | '/dashboard/forms'
    | '/dashboard/imports'
    | '/dashboard/insights'
    | '/dashboard/requests'
    | '/dashboard/testimonials'
    | '/dashboard/wall'
    | '/collect/$workspaceSlug/$formSlug'
    | '/dashboard/forms/create'
    | '/dashboard/settings/api-keys'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/team'
    | '/dashboard/settings/workspace'
    | '/dashboard/testimonials/$id'
    | '/dashboard/widgets/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/register'
    | '/dashboard/analytics'
    | '/dashboard/forms'
    | '/dashboard/imports'
    | '/dashboard/insights'
    | '/dashboard/requests'
    | '/dashboard/testimonials'
    | '/dashboard/wall'
    | '/collect/$workspaceSlug/$formSlug'
    | '/dashboard/forms/create'
    | '/dashboard/settings/api-keys'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/team'
    | '/dashboard/settings/workspace'
    | '/dashboard/testimonials/$id'
    | '/dashboard/widgets/create'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/register'
    | '/dashboard/analytics'
    | '/dashboard/forms'
    | '/dashboard/imports'
    | '/dashboard/insights'
    | '/dashboard/requests'
    | '/dashboard/testimonials'
    | '/dashboard/wall'
    | '/collect/$workspaceSlug/$formSlug'
    | '/dashboard/forms/create'
    | '/dashboard/settings/api-keys'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/team'
    | '/dashboard/settings/workspace'
    | '/dashboard/testimonials/$id'
    | '/dashboard/widgets/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  CollectWorkspaceSlugFormSlugRoute: typeof CollectWorkspaceSlugFormSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wall': {
      id: '/dashboard/wall'
      path: '/wall'
      fullPath: '/dashboard/wall'
      preLoaderRoute: typeof DashboardWallRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials': {
      id: '/dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/dashboard/testimonials'
      preLoaderRoute: typeof DashboardTestimonialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/requests': {
      id: '/dashboard/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof DashboardRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/imports': {
      id: '/dashboard/imports'
      path: '/imports'
      fullPath: '/dashboard/imports'
      preLoaderRoute: typeof DashboardImportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/forms': {
      id: '/dashboard/forms'
      path: '/forms'
      fullPath: '/dashboard/forms'
      preLoaderRoute: typeof DashboardFormsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/widgets/create': {
      id: '/dashboard/widgets/create'
      path: '/widgets/create'
      fullPath: '/dashboard/widgets/create'
      preLoaderRoute: typeof DashboardWidgetsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials/$id': {
      id: '/dashboard/testimonials/$id'
      path: '/$id'
      fullPath: '/dashboard/testimonials/$id'
      preLoaderRoute: typeof DashboardTestimonialsIdRouteImport
      parentRoute: typeof DashboardTestimonialsRoute
    }
    '/dashboard/settings/workspace': {
      id: '/dashboard/settings/workspace'
      path: '/settings/workspace'
      fullPath: '/dashboard/settings/workspace'
      preLoaderRoute: typeof DashboardSettingsWorkspaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/team': {
      id: '/dashboard/settings/team'
      path: '/settings/team'
      fullPath: '/dashboard/settings/team'
      preLoaderRoute: typeof DashboardSettingsTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/billing': {
      id: '/dashboard/settings/billing'
      path: '/settings/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/api-keys': {
      id: '/dashboard/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/dashboard/settings/api-keys'
      preLoaderRoute: typeof DashboardSettingsApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/forms/create': {
      id: '/dashboard/forms/create'
      path: '/create'
      fullPath: '/dashboard/forms/create'
      preLoaderRoute: typeof DashboardFormsCreateRouteImport
      parentRoute: typeof DashboardFormsRoute
    }
    '/collect/$workspaceSlug/$formSlug': {
      id: '/collect/$workspaceSlug/$formSlug'
      path: '/collect/$workspaceSlug/$formSlug'
      fullPath: '/collect/$workspaceSlug/$formSlug'
      preLoaderRoute: typeof CollectWorkspaceSlugFormSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardFormsRouteChildren {
  DashboardFormsCreateRoute: typeof DashboardFormsCreateRoute
}

const DashboardFormsRouteChildren: DashboardFormsRouteChildren = {
  DashboardFormsCreateRoute: DashboardFormsCreateRoute,
}

const DashboardFormsRouteWithChildren = DashboardFormsRoute._addFileChildren(
  DashboardFormsRouteChildren,
)

interface DashboardTestimonialsRouteChildren {
  DashboardTestimonialsIdRoute: typeof DashboardTestimonialsIdRoute
}

const DashboardTestimonialsRouteChildren: DashboardTestimonialsRouteChildren = {
  DashboardTestimonialsIdRoute: DashboardTestimonialsIdRoute,
}

const DashboardTestimonialsRouteWithChildren =
  DashboardTestimonialsRoute._addFileChildren(
    DashboardTestimonialsRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardFormsRoute: typeof DashboardFormsRouteWithChildren
  DashboardImportsRoute: typeof DashboardImportsRoute
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardTestimonialsRoute: typeof DashboardTestimonialsRouteWithChildren
  DashboardWallRoute: typeof DashboardWallRoute
  DashboardSettingsApiKeysRoute: typeof DashboardSettingsApiKeysRoute
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsTeamRoute: typeof DashboardSettingsTeamRoute
  DashboardSettingsWorkspaceRoute: typeof DashboardSettingsWorkspaceRoute
  DashboardWidgetsCreateRoute: typeof DashboardWidgetsCreateRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardFormsRoute: DashboardFormsRouteWithChildren,
  DashboardImportsRoute: DashboardImportsRoute,
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardTestimonialsRoute: DashboardTestimonialsRouteWithChildren,
  DashboardWallRoute: DashboardWallRoute,
  DashboardSettingsApiKeysRoute: DashboardSettingsApiKeysRoute,
  DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
  DashboardSettingsTeamRoute: DashboardSettingsTeamRoute,
  DashboardSettingsWorkspaceRoute: DashboardSettingsWorkspaceRoute,
  DashboardWidgetsCreateRoute: DashboardWidgetsCreateRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  CollectWorkspaceSlugFormSlugRoute: CollectWorkspaceSlugFormSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
